// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CreateTaskController from "./create_task_controller"
application.register("create-task", CreateTaskController)

import EditInTaskController from "./edit_in_task_controller"
application.register("edit-in-task", EditInTaskController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import SortableController from "./sortable_controller"
application.register("sortable", SortableController)

/*import { initSortable } from "./plugins/init_sortable"
initSortable()*/

const list = document.querySelector("#steps")

import Sortable from "sortablejs"
const csrfToken = document.head.querySelector("[name='csrf-token']").content;

const initSortable = () => {
  Sortable.create(list, {
    ghostClass: "ghost",
    animation: 150,
    onEnd: (event) => {
      alert(`${event.oldIndex} moved to ${event.newIndex}`)
      fetch(`/steps/update?old_index=${event.oldIndex + 1}&new_index=${event.newIndex + 1}`, {
        method: "PATCH",
        headers: {
          'Accept': 'application/json',
          'Content-Type': 'application/json',
          'X-Requested-With': 'XMLHttpRequest',
          'X-CSRF-Token': csrfToken
        },
        body: JSON.stringify({steps: {old_index: event.oldIndex, new_index: event.newIndex}})
      })
      .then((response) => {
        if (response.ok) {
          return response.json()
        } else {
          alert("Erro na requisição")
        }
      })
      .then((data) => {
        console.log(data)
      })
    }
  })
}

initSortable()
